src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $Name;

    /**
     * @ORM\OneToMany(targetEntity=Activity::class, mappedBy="Category")
     */
    private $activities;

    /**
     * @ORM\OneToMany(targetEntity=Course::class, mappedBy="Category")
     */
    private $courses;

    /**
     * @ORM\OneToMany(targetEntity=Exercice::class, mappedBy="Category")
     */
    private $exercices;

    /**
     * @ORM\OneToMany(targetEntity=Project::class, mappedBy="Category")
     */
    private $projects;

    public function __construct()
    {
        $this->activities = new ArrayCollection();
        $this->courses = new ArrayCollection();
        $this->exercices = new ArrayCollection();
        $this->projects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    /**
     * @return Collection|Activity[]
     */
    public function getActivities(): Collection
    {
        return $this->activities;
    }

    public function addActivity(Activity $activity): self
    {
        if (!$this->activities->contains($activity)) {
            $this->activities[] = $activity;
            $activity->setCategory($this);
        }

        return $this;
    }

    public function removeActivity(Activity $activity): self
    {
        if ($this->activities->removeElement($activity)) {
            // set the owning side to null (unless already changed)
            if ($activity->getCategory() === $this) {
                $activity->setCategory(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Course[]
     */
    public function getCourses(): Collection
    {
        return $this->courses;
    }

    public function addCourse(Course $course): self
    {
        if (!$this->courses->contains($course)) {
            $this->courses[] = $course;
            $course->setCategory($this);
        }

        return $this;
    }

    public function removeCourse(Course $course): self
    {
        if ($this->courses->removeElement($course)) {
            // set the owning side to null (unless already changed)
            if ($course->getCategory() === $this) {
                $course->setCategory(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Exercice[]
     */
    public function getExercices(): Collection
    {
        return $this->exercices;
    }

    public function addExercice(Exercice $exercice): self
    {
        if (!$this->exercices->contains($exercice)) {
            $this->exercices[] = $exercice;
            $exercice->setCategory($this);
        }

        return $this;
    }

    public function removeExercice(Exercice $exercice): self
    {
        if ($this->exercices->removeElement($exercice)) {
            // set the owning side to null (unless already changed)
            if ($exercice->getCategory() === $this) {
                $exercice->setCategory(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Project[]
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): self
    {
        if (!$this->projects->contains($project)) {
            $this->projects[] = $project;
            $project->setCategory($this);
        }

        return $this;
    }

    public function removeProject(Project $project): self
    {
        if ($this->projects->removeElement($project)) {
            // set the owning side to null (unless already changed)
            if ($project->getCategory() === $this) {
                $project->setCategory(null);
            }
        }

        return $this;
    }

    /**
     * @return String
     */
    public function __toString() : String
    {
        return $this->getName();
    }
}

src/Entity/Course.php
<?php

namespace App\Entity;

use App\Repository\CourseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CourseRepository::class)
 */
class Course
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=450)
     */
    private $Summary;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="courses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Category;

    /**
     * @ORM\Column (type="string", length=255)
     *
     * @Gedmo\Slug(fields={"Title"})
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=CourseChapter::class, mappedBy="Course")
     */
    private $courseChapters;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Range(
     *     min=1,
     *     max=5,
     *     notInRangeMessage="La note de difficulté doit être comprise dans [1;5]"
     * )
     */
    private $Difficulty;

    /**
     * @ORM\Column(type="boolean")
     */
    private $IsVisible;

    /**
     * @ORM\Column(type="array")
     */
    private $Prerequisites = [];

    public function __construct()
    {
        $this->courseChapters = new ArrayCollection();
        $this->CreatedAt = new \DateTime();
        $this->Prerequisites = [];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = new \DateTimeImmutable();

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->Summary;
    }

    public function setSummary(string $Summary): self
    {
        $this->Summary = $Summary;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function setSlug(string $slug) : self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getSlug() : ?string
    {
        return $this->slug;
    }

    /**
     * @return Collection|CourseChapter[]
     */
    public function getCourseChapters(): Collection
    {
        return $this->courseChapters;
    }

    public function addCourseChapter(CourseChapter $courseChapter): self
    {
        if (!$this->courseChapters->contains($courseChapter)) {
            $this->courseChapters[] = $courseChapter;
            $courseChapter->setCourse($this);
        }

        return $this;
    }

    public function removeCourseChapter(CourseChapter $courseChapter): self
    {
        if ($this->courseChapters->removeElement($courseChapter)) {
            // set the owning side to null (unless already changed)
            if ($courseChapter->getCourse() === $this) {
                $courseChapter->setCourse(null);
            }
        }

        return $this;
    }

    public function __toString():String
    {
        return $this->getTitle();
    }

    public function getDifficulty(): ?int
    {
        return $this->Difficulty;
    }

    public function setDifficulty(int $Difficulty): self
    {
        $this->Difficulty = $Difficulty;

        return $this;
    }

    public function getIsVisible(): ?bool
    {
        return $this->IsVisible;
    }

    public function setIsVisible(bool $IsVisible): self
    {
        $this->IsVisible = $IsVisible;

        return $this;
    }

    public function getPrerequisites(): ?array
    {
        return $this->Prerequisites;
    }

    public function setPrerequisites(array $Prerequisites): self
    {
        $this->Prerequisites = $Prerequisites;

        return $this;
    }
}

templates/pages/exerciceList.html.twig
{% extends 'base.html.twig' %}
{% set break = false %}
{% block title %}Exercices{% endblock %}
{% block body %}
    <h1 class="text-center">Tous les exercices</h1>
    <div class="d-flex container flex-wrap flex-row justify-content-around">
        {% for exercice in exercices %}
            <div class="card shadow my-5" style="width: 18rem;">
                <div class="card-body ">
                    <h5 class="card-title"><a href="{{ path('exercice_post_show', {"slug": exercice.slug}) }}">{{ exercice.title }}</a></h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ exercice.category.name }}</h6>
                    <p class="card-text summary ">{{ exercice.content }}.</p>
                    <p class="card-text text-secondary">Ajouté le {{ exercice.createdAt|date('d/m/Y') }}</p>
                    <p class="card-text text-secondary">Difficulté :
                        {% for i in 0..exercice.difficulty %}
                            {% if i != 0 %}
                                ⭐
                            {% endif %}
                        {% endfor %}
                    </p>
                    {% if exercice.slug in progs %}
                        <a href="{{ path('exercice_post_show', {"slug": exercice.slug}) }}" class="btn btn-warning">Exercice Réalisé</a>
                    {% else %}
                        <a href="{{ path('exercice_post_show', {"slug": exercice.slug}) }}" class="btn btn-primary">Faire l'exercice</a>
                    {% endif%}
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="d-flex justify-content-center m-5">
        {{ knp_pagination_render(exercices) }}
    </div>

{% endblock %}

templates/pages/generalList.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ contentName|capitalize }}{% endblock %}

{% block body %}
    <h1 class="text-center">
        {% if contentName == "activités" %}
            Toutes les {{ contentName }}
        {% else %}
            Tous les {{ contentName }}
        {% endif %}
    </h1>
    {% if contents %}
        <div id="list" class="d-flex flex-row flex-wrap container justify-content-around">
            {% for content in contents %}
                <div class="card shadow my-5" style="width: 18rem;">
                    <div class="card-body ">
                        <h5 class="card-title"><a href="{{ contentName|replace({"é": "e"}) }}/{{ content.slug }}">{{ content.title }}</a></h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ content.category.name }}</h6>
                        <p class="card-text summary ">{{ content.summary }}</p>
                        <p class="card-text text-secondary">Ajouté le {{ content.createdAt|date("d/m/Y") }}</p>
                        <p class="card-text text-secondary">Difficulté :
                            {% for i in 0..content.difficulty %}
                                {% if i != 0 %}
                                    ⭐
                                {% endif %}
                            {% endfor %}
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="d-flex justify-content-center m-5">
            {{ knp_pagination_render(contents) }}
        </div>

    {% else %}
        <div class="alert alert-warning text-center" role="alert">
            Aucun contenu n'est disponible pour le moment
        </div>
    {% endif %}
{% endblock %}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block title %} Accueil {% endblock %}

{% block body %}
    <div id="main-container" class="d-flex flex-row align-items-center justify-content-between">
        <section>
            <h1 class="text-uppercase">Apprenez, où vous voulez quand vous voulez</h1>
            <p>Il est possible d’apprendre grâce à plusieurs formats, des activités, des exercices, des vidéos et des projets pour apprendre tout en pratiquant !</p>
        </section>
        <object data="/assets/laptopIllustration.svg"></object>
    </div>
    <div id="actu-container">
        <div class="d-flex w-75 mx-auto flex-wrap justify-content-around" id="actus">
            <section class="actus-group border border-1 my-5 p-4 position-relative"> <!-- Last lessons -->
                <h3 class="rounded-pill d-inline-block p-2 position-absolute">Les derniers cours</h3>
                {% if courses %}
                    {% for course in courses %}
                        <section>
                            <h2><a href="{{ path('course_post_show', {'slug': course.slug}) }}">{{ course.title }}</a></h2>
                            <p>Ajouté le :  {{ course.createdAt|date("d/m/Y") }}</p>
                        </section>
                        {% if courses[0] == course or courses[1] == course%}
                            <hr class="my-3">
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <div class="alert alert-warning text-center" role="alert">
                        Aucun contenu n'est disponible pour le moment
                    </div>
                {% endif  %}
            </section>
            <section class="actus-group border border-1 my-5 p-4 position-relative"> <!-- Last projects -->
                <h3 class="rounded-pill d-inline-block p-2 position-absolute green-text">Les derniers projets</h3>
                {% if projects %}
                    {% for project in projects %}
                        <section>
                            <h2><a href="{{ path('project_post_show', {'slug': project.slug}, relative = false) }}">{{ project.title }}</a></h2>
                            <p>Ajouté le :  {{ project.createdAt|date("d/m/Y") }}</p>
                        </section>
                        {% if projects[0] == project or projects[1] == project%}
                            <hr class="my-3">
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <div class="alert alert-warning text-center" role="alert">
                        Aucun contenu n'est disponible pour le moment
                    </div>
                {% endif  %}

            </section>
            <section class="actus-group border border-1 my-5 p-4 position-relative"> <!-- Last activities -->
                <h3 class="rounded-pill d-inline-block p-2 position-absolute green-text">Les dernières activités</h3>
                {% if activities %}
                    {% for activity in activities %}
                        <section>
                            <h2><a href="{{ path('activity_post_show', {'slug': activity.slug}, relative = false) }}">{{ activity.title }}</a></h2>
                            <p>Ajouté le :  {{ activity.createdAt|date("d/m/Y") }}</p>
                        </section>
                        {% if activities[0] == activity or activities[1] == activity %}
                            <hr class="my-3">
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <div class="alert alert-warning text-center" role="alert">
                        Aucun contenu n'est disponible pour le moment
                    </div>
                {% endif  %}
            </section>
            <section class="actus-group border border-1 my-5 p-4 position-relative"> <!-- Last exercises -->
                <h3 class="rounded-pill d-inline-block p-2 position-absolute ">Les derniers exercices</h3>
                {% if exercises %}
                    {% for exercice in exercises %}
                        <section>
                            <h2><a href="">{{ exercice.title }}</a></h2>
                            <p>Ajouté le :  {{ exercice.createdAt|date("d/m/Y") }}</p>
                        </section>
                        {% if exercises[0] == exercice or exercises[1] == exercice %}
                            <hr class="my-3">
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <div class="alert alert-warning text-center" role="alert">
                        Aucun contenu n'est disponible pour le moment
                    </div>
                {% endif  %}
            </section>
        </div>
    </div>
{% endblock %}

templates/pages/showActivity.html.twig
{% extends "base.html.twig" %}
{% block title %} {{ activity.Title }} {% endblock %}
{% block body %}
    <p class="redirect m-3"><a href="{{ path('activity_list') }}">Activités</a> > {{ activity.Title }} > {{ currentChapter.title }} </p>
    <h1 class="content-title text-center">{{ activity.title }}</h1>
    <div class="intro-container d-flex flex-row justify-content-around">
        <aside class="">
            <section class="border my-3 shadow p-2">
                <h3>Informations :</h3>
                <ul>
                    <li>Temps estimé : {{ time }} minutes</li>
                    <li>X chapitres</li>
                    <li>Ajouté le {{ activity.createdAt|date("d/m/Y") }}</li>
                </ul>
            </section>
            <section class="border my-3 shadow p-2">
                <h3>Chapitres :</h3>
                <ul>
                    {% for chapter in chapters %}
                        {% if chapter.slug in slugs %}
                            <li><span style="text-decoration: line-through;"><a class="text-secondary" href="{{ path('activity_chapter_show', {'activitySlug': activity.slug, 'chapterSlug': chapter.slug}) }}">{{ chapter.title }}</a></span></li>
                        {% else %}
                            <li><a href="{{ path('activity_chapter_show', {'activitySlug': activity.slug, 'chapterSlug': chapter.slug}) }}">{{ chapter.title }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </section>
            <section class="border my-3 shadow p-2">
                <h3>Pré-requis</h3>
                <ul>
                    {% for pre in activity.prerequisites %}
                        <li>{{ pre }}</li>
                    {% endfor %}
                </ul>
            </section>
        </aside>
        <div class="resume my-auto shadow p-3">
            <h3>Présentation</h3>
            <p>{{ activity.summary }}</p>
        </div>
    </div>
    <hr class="m-4">
    <div class="content-container w-75">
        {% if chapters is empty %}
            <div class="alert alert-warning" role="alert">
                Aucun chapitre n'est disponible, reviens plus tard...
            </div>
        {% else %}
            <h1>{{ currentChapter.title }}</h1>
            {{ currentChapter.content|raw }}

            {% if currentChapter.slug in slugs %}
                <div class="text-center my-3">
                    <button type="button" class="btn btn-info" disabled>J'ai déjà lu ce chapitre</button>
                </div>
            {% else %}
                <div class="text-center my-3">
                    <button type="button" class="btn btn-success" onclick="location.href ='/markAsRead/activity/{{ currentChapter.slug }}'">J'ai lu ce chapitre</button>
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

templates/pages/showCourse.html.twig
{% extends "base.html.twig" %}
{% block title %} {{ course.title }} {% endblock %}
{% block body %}
    <p class="redirect m-3"><a href="{{ path('course_list') }}">Cours</a> > {{ course.Title }} > {{ currentChapter.title }}</p>
    <h1 class="content-title text-center">{{ course.title }}</h1>
    <div class="intro-container d-flex flex-row justify-content-around">
        <aside class="">
            <section class="border my-3 shadow p-2">
                <h3>Informations :</h3>
                <ul>
                    <li>Temps estimé : {{ time }} minutes</li>
                    <li>X chapitres</li>
                    <li>Ajouté le {{ course.createdAt|date("d/m/Y") }}</li>
                </ul>
            </section>
            <section class="border my-3 shadow p-2">
                <h3>Chapitres :</h3>
                <ul>
                    {% for chapter in chapters %}
                        {% if chapter.slug in slugs %}
                            <li><span style="text-decoration: line-through;"><a class="text-secondary" href="{{ path('course_chapter_show', {'courseSlug': course.slug, 'chapterSlug': chapter.slug}) }}">{{ chapter.title }}</a></span></li>
                        {% else %}
                            <li><a href="{{ path('course_chapter_show', {'courseSlug': course.slug, 'chapterSlug': chapter.slug}) }}">{{ chapter.title }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </section>
            <section class="border my-3 shadow p-2">
                <h3>Pré-requis</h3>
                <ul>
                    {% for pre in course.prerequisites %}
                        <li>{{ pre }}</li>
                    {% endfor %}
                </ul>
            </section>
        </aside>
        <div class="resume my-auto shadow p-3">
            <h3>Présentation</h3>
            <p>{{ course.summary }}</p>
        </div>
    </div>
    <hr class="m-4">
    <div class="content-container w-75">
        {% if chapters is empty %}
            <div class="alert alert-warning" role="alert">
                Aucun chapitre n'est disponible, reviens plus tard...
            </div>
        {% else %}
            <h1>{{ currentChapter.title }}</h1>
            <p>{{ currentChapter.content|raw }}</p>

            {% if currentChapter.slug in slugs %}
                <div class="text-center my-3">
                    <button type="button" class="btn btn-info" disabled>J'ai déjà lu ce chapitre</button>
                </div>
            {% else %}
                <div class="text-center my-3">
                    <button type="button" class="btn btn-success" onclick="location.href ='/markAsRead/course/{{ currentChapter.slug }}'">J'ai lu ce chapitre</button>
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

templates/pages/showExercice.html.twig
{% extends "base.html.twig" %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
    <div class="jumbotron jumbotron-fluid my-0">
        <div class="container">
            <div class="d-flex flex-row justify-content-between align-items-center">
                <h1 class="display-4">{{ title }}</h1>
                <p><button type="button" class="btn btn-success" onclick="location.href ='/markAsRead/exercice/{{ slug }}'">J'ai fais cet exercice.</button></p>
            </div>
            <div class="lead"> {{ content | markdown_to_html }} </div>
        </div>
        <div class="d-flex flex-row justify-content-around align-items-center ">
            <button type="button" class="btn btn-warning mx-3 help-bouton">Afficher l'aide</button>
            <button type="button" class="btn btn-info mx-3 solution-button">Afficher la solution</button>
        </div>
    </div>

    <div class="jumbotron jumbotron-fluid mx-auto w-75 mt-4 help-container">
        <div class="container ">
            <h1 class="display-4">Aide</h1>
            <div class="lead">{{ help | markdown_to_html }}</div>
        </div>
    </div>
    <div class="jumbotron jumbotron-fluid mx-auto w-75 mt-4 solution-container">
        <div class="container">
            <h1 class="display-4">Solution</h1>
            <div class="lead">{{ correction | raw }}</div>
        </div>
    </div>
{% endblock %}

templates/pages/showProject.html.twig
{% extends "base.html.twig" %}
{% block title %} {{ project.Title }} {% endblock %}
{% block body %}
    <p class="redirect m-3"><a href="{{ path('project_list') }}">Projets</a> > {{ project.Title }} > {{ currentChapter.title }} </p>
    <h1 class="content-title text-center">{{ project.title }}</h1>
    <div class="intro-container d-flex flex-row justify-content-around">
        <aside class="">
            <section class="border my-3 shadow p-2">
                <h3>Informations :</h3>
                <ul>
                    <li>Temps estimé : {{ time }} minutes</li>
                    <li>X chapitres</li>
                    <li>Ajouté le {{ project.createdAt|date("d/m/Y") }}</li>
                </ul>
            </section>
            <section class="border my-3 shadow p-2">
                <h3>Chapitres :</h3>
                <ul>
                    {% for chapter in chapters %}
                        {% if chapter.slug in slugs %}
                            <li><span style="text-decoration: line-through;"><a class="text-secondary" href="{{ path('project_chapter_show', {'projectSlug': project.slug, 'chapterSlug': chapter.slug}) }}">{{ chapter.title }}</a></span></li>
                        {% else %}
                            <li><a href="{{ path('project_chapter_show', {'projectSlug': project.slug, 'chapterSlug': chapter.slug}) }}">{{ chapter.title }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </section>
            <section class="border my-3 shadow p-2">
                <h3>Pré-requis</h3>
                <ul>
                    {% for pre in project.prerequisites %}
                        <li>{{ pre }}</li>
                    {% endfor %}
                </ul>
            </section>
        </aside>
        <div class="resume my-auto shadow p-3">
            <h3>Présentation</h3>
            <p>{{ project.summary }}</p>
        </div>
    </div>
    <hr class="m-4">
    <div class="content-container w-75">
        {% if chapters is empty %}
            <div class="alert alert-warning" role="alert">
                Aucun chapitre n'est disponible, reviens plus tard...
            </div>
        {% else %}
            <h1>{{ currentChapter.title }}</h1>
            {{ currentChapter.content | raw }}

            {% if currentChapter.slug in slugs %}
                <div class="text-center my-3">
                    <button type="button" class="btn btn-info" disabled>J'ai déjà lu ce chapitre</button>
                </div>
            {% else %}
                <div class="text-center my-3">
                    <button type="button" class="btn btn-success" onclick="location.href ='/markAsRead/project/{{ currentChapter.slug }}'">J'ai lu ce chapitre</button>
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}